# Generated by Django 5.0.6 on 2024-06-29 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
