# Generated by Django 5.0.6 on 2024-06-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
