# Generated by Django 5.0.6 on 2024-07-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_has_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_variants',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='flavour',
        ),
    ]
