# Generated by Django 5.0.6 on 2024-07-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_has_variants_remove_variant_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='flavour_notes',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='roast',
        ),
        migrations.AddField(
            model_name='product',
            name='flavour_notes',
            field=models.CharField(blank=True, default=False, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='roast',
            field=models.CharField(blank=True, default=False, max_length=254, null=True),
        ),
    ]
