# Generated by Django 5.0.6 on 2024-07-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_variant_flavour_notes_remove_variant_roast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
