# Generated by Django 5.0.6 on 2024-07-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=6),
            preserve_default=False,
        ),
    ]
